// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export const options = {
  maxRedirects: 4,
  duration: '1m',
  vus: 100,
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "Get Entries",
    id: "6f62b1ad-9de3-454b-82e6-b4dbe292eac6",
    method: "GET",
    address: "https://api.publicapis.org/entries",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "Cat Fast",
    id: "0ca69f0c-417d-4b2f-9d74-edd22683c334",
    method: "GET",
    address: "https://catfact.ninja/fact",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "View the Bitcoin Price Index (BPI) in real-time.",
    id: "20feb846-366f-4b59-869a-4d06cbb02781",
    method: "GET",
    address: "https://api.coindesk.com/v1/bpi/currentprice.json",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });
}
